/* Studio copy extends the existing site language system. */
window.MINIFOX_STUDIO = {
 en: {
  studio_label:"FOR CREATORS",studio_our:"Our AI Studio",studio_preview:"Development preview",studio_intro:"One workspace for your video workflow. Plan ideas, generate assets and bring your channels together.",studio_video:"Video & Shorts",studio_music:"Music",studio_explore:"Discover AI Studio →",studio_soon:"Sales opening soon",
  studio_hero:"Your creative workflow.",studio_hero2:"One AI Studio.",studio_lead:"From an idea to a video: organise your channels, work with AI tools and manage production in one desktop workspace.",studio_buy:"Buy AI Studio",studio_see:"Explore the studio",studio_platform:"Windows first · Customer release in final testing",
  studio_features:"More creating. Less switching tools.",studio_features_d:"A connected workspace for the everyday steps of video production — with you in control of what gets published.",
  studio_f1:"Channel profiles",studio_d1:"Keep each channel’s topics, settings and production workflow in its own profile.",studio_f2:"Ideas & scripts",studio_d2:"Develop topics and work on scripts as part of the production pipeline.",studio_f3:"Visuals & voice",studio_d3:"Connect image and voice tools to prepare the assets your video needs.",studio_f4:"Video production",studio_d4:"Manage video and Shorts jobs, rendering and output from one production queue.",studio_f5:"Music workflows",studio_d5:"Work with ACE-Step for music generation. Long-form music production is still being validated.",studio_f6:"YouTube insights",studio_d6:"Connect your channel to view available analytics. Google authorisation is required; some metrics may be unavailable.",
  studio_flow:"A clear path from idea to output.",studio_step1:"Plan",studio_step1_d:"Choose a channel, topic and brief.",studio_step2:"Create",studio_step2_d:"Prepare scripts, voice and visuals with your configured tools.",studio_step3:"Review",studio_step3_d:"Check the result and adjust your production settings.",studio_step4:"Publish",studio_step4_d:"Use your connected YouTube account and chosen upload settings.",
  studio_screens:"A look inside the studio.",studio_dashboard:"Dashboard — channels, production controls and available analytics.",studio_production:"Production setup — project, brief and workflow in one place.",studio_screenshot_note:"Real screenshots of the current development build. The interface and feature availability may change before release. Click an image to view it at full size.",
  studio_before:"Before you get started.",studio_require:"Setup & requirements",studio_r1:"The Windows customer installer is in final testing. A macOS release is not yet confirmed.",studio_r2:"Local AI tools and models need suitable hardware. Final minimum requirements will be published with the release.",studio_r3:"YouTube features require your own account and channel authorisation.",studio_license:"License & services",studio_l1:"First activation needs an internet connection. The license must be confirmed online at least once every 7 days.",studio_l2:"The Studio price does not include paid third-party services, model subscriptions or provider credits.",studio_l3:"License terms, device allowance, support and refund conditions will be published before checkout opens.",
  studio_pricing:"Your next creative workspace.",studio_price_d:"AI Studio brings the production process together, so you can spend more time shaping your content.",studio_price_label:"PLANNED RELEASE PRICE",studio_price_note:"Sales are not open yet. This button does not take payment or issue a license.",studio_faq_title:"A few things worth knowing.",studio_q1:"Can I buy it today?",studio_a1:"Not yet. We are finishing customer installation and end-to-end tests. Checkout and final sale terms will be added here when sales open.",studio_q2:"Is every mode ready for release?",studio_a2:"No. Some modes and integrations are still being tested. The final release feature list will be confirmed before purchase; preview screenshots are not a guarantee of availability.",studio_q3:"Does Studio guarantee views or revenue?",studio_a3:"No. Studio is a production tool. You remain responsible for reviewing content, model licenses and the rules of each publishing platform.",studio_q4:"Where can I ask a question?",studio_a4:"Contact support@minifoxlabs.com for product and release questions.",studio_dialog_title:"Sales opening soon",studio_dialog_text:"AI Studio’s planned price is $199 USD. Checkout will be connected after final testing. No payment has been taken and no license has been issued.",studio_close:"Got it",studio_back:"← Mini Fox Labs"
 },
 ru: {
  studio_label:"ДЛЯ АВТОРОВ",studio_our:"Наша AI Studio",studio_preview:"Предварительная версия",studio_intro:"Единое пространство для создания видео: планируйте идеи, генерируйте материалы и управляйте своими каналами.",studio_video:"Видео и Shorts",studio_music:"Музыка",studio_explore:"Познакомиться с AI Studio →",studio_soon:"Продажи скоро откроются",
  studio_hero:"Ваш творческий процесс.",studio_hero2:"Одна AI Studio.",studio_lead:"От идеи до видео: управляйте каналами, работайте с ИИ-инструментами и ведите производство в одном приложении для компьютера.",studio_buy:"Купить AI Studio",studio_see:"Посмотреть возможности",studio_platform:"Сначала Windows · Клиентская версия проходит финальные проверки",
  studio_features:"Больше творчества. Меньше переключений.",studio_features_d:"Общее рабочее пространство для повседневных этапов создания видео. Решение о публикации остаётся за вами.",
  studio_f1:"Профили каналов",studio_d1:"Храните темы, настройки и процесс производства каждого канала в отдельном профиле.",studio_f2:"Идеи и сценарии",studio_d2:"Развивайте темы и работайте со сценариями в рамках общего производственного процесса.",studio_f3:"Изображения и голос",studio_d3:"Подключайте инструменты генерации изображений и озвучки для подготовки материалов видео.",studio_f4:"Производство видео",studio_d4:"Управляйте заданиями для видео и Shorts, сборкой и результатами в единой очереди.",studio_f5:"Музыкальные проекты",studio_d5:"Используйте ACE-Step для генерации музыки. Производство длинных музыкальных роликов ещё проверяется.",studio_f6:"Статистика YouTube",studio_d6:"Подключите канал для просмотра доступной статистики. Нужна авторизация Google; отдельные показатели могут быть недоступны.",
  studio_flow:"Понятный путь от идеи до результата.",studio_step1:"Планирование",studio_step1_d:"Выберите канал, тему и описание задачи.",studio_step2:"Создание",studio_step2_d:"Подготовьте сценарий, голос и изображения с настроенными инструментами.",studio_step3:"Проверка",studio_step3_d:"Просмотрите результат и скорректируйте параметры производства.",studio_step4:"Публикация",studio_step4_d:"Используйте подключённый аккаунт YouTube и выбранные настройки загрузки.",
  studio_screens:"Загляните внутрь студии.",studio_dashboard:"Главный экран — каналы, управление производством и доступная статистика.",studio_production:"Настройка ролика — проект, описание задачи и рабочий процесс в одном месте.",studio_screenshot_note:"Реальные скриншоты текущей разрабатываемой версии. Интерфейс и доступность функций могут измениться до релиза. Нажмите на изображение, чтобы открыть его в полном размере.",
  studio_before:"Перед началом работы.",studio_require:"Установка и требования",studio_r1:"Клиентский установщик Windows проходит финальные проверки. Выпуск для macOS пока не подтверждён.",studio_r2:"Локальным ИИ-инструментам и моделям требуется подходящее оборудование. Минимальные требования будут опубликованы к релизу.",studio_r3:"Для функций YouTube нужны собственный аккаунт и разрешение доступа к каналу.",studio_license:"Лицензия и сервисы",studio_l1:"Для первой активации нужен интернет. Лицензию необходимо подтверждать онлайн не реже раза в 7 дней.",studio_l2:"В цену студии не входят платные сторонние сервисы, подписки на модели и кредиты провайдеров.",studio_l3:"Условия лицензии, лимит устройств, поддержка и правила возврата будут опубликованы до открытия оплаты.",
  studio_pricing:"Ваше новое творческое пространство.",studio_price_d:"AI Studio объединяет этапы производства, чтобы больше времени оставалось на содержание ваших роликов.",studio_price_label:"ПЛАНИРУЕМАЯ ЦЕНА РЕЛИЗА",studio_price_note:"Продажи ещё не открыты. Эта кнопка не принимает оплату и не выдаёт лицензию.",studio_faq_title:"Что важно знать.",studio_q1:"Можно купить прямо сейчас?",studio_a1:"Пока нет. Мы завершаем проверку клиентской установки и полного производственного цикла. Оплата и окончательные условия продажи появятся здесь при запуске.",studio_q2:"Все режимы уже готовы к релизу?",studio_a2:"Нет. Некоторые режимы и интеграции ещё проходят тестирование. Список функций релиза будет подтверждён до покупки; скриншоты предварительной версии не гарантируют их доступность.",studio_q3:"Студия гарантирует просмотры или доход?",studio_a3:"Нет. Студия — инструмент производства. За проверку контента, условий использования моделей и правил платформ отвечает автор.",studio_q4:"Где задать вопрос?",studio_a4:"По вопросам продукта и выпуска пишите на support@minifoxlabs.com.",studio_dialog_title:"Продажи скоро откроются",studio_dialog_text:"Планируемая цена AI Studio — $199 USD. Оплату подключим после финальных проверок. Деньги не списаны, лицензия не выдана.",studio_close:"Понятно",studio_back:"← Mini Fox Labs"
 }
};
